/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CTPhanQuyenBUS;
import BUS.ChucNangBUS;
import BUS.NhomQuyenBUS;
import DTO.CTQuyenDTO;
import Util.sharedFunction;
import java.awt.BorderLayout;
import java.awt.Color;

import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public final class ChiTietQuyen extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietQuyen
     */
    private static JTable tableCTQuyen;
    private static DefaultTableModel modelCTQuyen;
    ChucNangBUS cnBUS = new ChucNangBUS();
    NhomQuyenBUS nqBUS = new NhomQuyenBUS();
    CTPhanQuyenBUS ctqBUS = new CTPhanQuyenBUS();
    private PhanQuyenGUI nqGUI;

    public ChiTietQuyen(PhanQuyenGUI nqGUI) {
        this.nqGUI = nqGUI;
        this.setUndecorated(true);
        initComponents();

        createTable();

        this.setLocationRelativeTo(null);
    }

    public static DefaultTableModel getModelCTQuyen() {
        return modelCTQuyen;
    }

    public JPanel getPnTable() {
        return pnTable;
    }

    public static JTable getTableCTQuyen() {
        return tableCTQuyen;
    }

    public void createTable() {
        String[] columnNames = {"ID", "Tên Chức Năng", "Hành Động", ""};
        modelCTQuyen = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 3:
                        return Boolean.class;
                    default:
                        return String.class;
                }
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return column == 3;
            }

        };
        modelCTQuyen.setColumnIdentifiers(columnNames);
        // Tạo JTable với DefaultTableModel
        tableCTQuyen = new JTable(modelCTQuyen);

        TableColumnModel columnModel = tableCTQuyen.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(85); // Độ rộng cột 0
        columnModel.getColumn(1).setPreferredWidth(150); // Độ rộng cột 1
        columnModel.getColumn(2).setPreferredWidth(150); // Độ rộng cột 2
        columnModel.getColumn(3).setPreferredWidth(80); // Độ rộng cột 3

        sharedFunction.EditHeaderTable(tableCTQuyen);
        editTableContent(tableCTQuyen);

        tableCTQuyen.setPreferredScrollableViewportSize(pnTable.getPreferredSize());
        JScrollPane scrollPaneSanPham = new JScrollPane(tableCTQuyen);
        MatteBorder matteBorder = new MatteBorder(0, 1, 1, 1, new Color(164, 191, 226));
        scrollPaneSanPham.setBorder(matteBorder);
        pnTable.setLayout(new BorderLayout());
        pnTable.add(scrollPaneSanPham);

        cnBUS.createTableCTQ(modelCTQuyen);

    }

    public void editTableContent(JTable table) {
        int rowHeight = 30;
        table.setRowHeight(rowHeight);
        table.setGridColor(new Color(153, 184, 224));
        table.setShowGrid(true);
        table.setBackground(Color.WHITE);
        table.setSelectionForeground(new Color(253, 191, 84));
        table.setSelectionBackground(Color.WHITE);
        table.setFocusable(false);
        table.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Font font = new Font("Segoe UI", Font.PLAIN, 14);
        table.setFont(font);
        // Căn giữa nội dung trong các ô chữ
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < table.getColumnCount() - 1; i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            table.setEditingColumn(i);
        }
    }

    public JTextField getTxtDes() {
        return txtDes;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOverview = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblThongTinChiTiet = new javax.swing.JLabel();
        txtDes = new javax.swing.JTextField();
        lblChiTietQuyen = new javax.swing.JLabel();
        lblTenNhomQuyen = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblMoTa = new javax.swing.JLabel();
        btnHuy = new Components.ButtonRadius();
        btnLuu = new Components.ButtonRadius();
        pnTable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelOverview.setBackground(new java.awt.Color(255, 255, 255));

        lblID.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(148, 181, 222));
        lblID.setText("ID Quyền");

        lblThongTinChiTiet.setBackground(new java.awt.Color(153, 204, 255));
        lblThongTinChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThongTinChiTiet.setForeground(new java.awt.Color(102, 102, 102));
        lblThongTinChiTiet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongTinChiTiet.setText("Thông tin chi tiết");
        lblThongTinChiTiet.setAutoscrolls(true);
        lblThongTinChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblThongTinChiTiet.setOpaque(true);

        txtDes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 210, 235), 2));

        lblChiTietQuyen.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblChiTietQuyen.setForeground(new java.awt.Color(148, 181, 222));
        lblChiTietQuyen.setText("Chi tiết quyền");

        lblTenNhomQuyen.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblTenNhomQuyen.setForeground(new java.awt.Color(148, 181, 222));
        lblTenNhomQuyen.setText("Tên nhóm quyền");

        txtID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 210, 235), 2));
        txtID.setFocusable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 210, 235), 2));

        lblMoTa.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblMoTa.setForeground(new java.awt.Color(148, 181, 222));
        lblMoTa.setText("Mô tả");

        btnHuy.setBackground(new java.awt.Color(153, 204, 255));
        btnHuy.setBorder(null);
        btnHuy.setForeground(new java.awt.Color(102, 102, 102));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_24px/cancel.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setColor(new java.awt.Color(153, 204, 255));
        btnHuy.setFocusPainted(false);
        btnHuy.setFont(new java.awt.Font("Josefin Sans SemiBold", 1, 18)); // NOI18N
        btnHuy.setRadius(40);
        btnHuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHuyMouseExited(evt);
            }
        });
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(153, 204, 255));
        btnLuu.setBorder(null);
        btnLuu.setForeground(new java.awt.Color(102, 102, 102));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_24px/fix.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setColor(new java.awt.Color(153, 204, 255));
        btnLuu.setFocusPainted(false);
        btnLuu.setFont(new java.awt.Font("Josefin Sans SemiBold", 1, 18)); // NOI18N
        btnLuu.setRadius(40);
        btnLuu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLuuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLuuMouseExited(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        pnTable.setMaximumSize(new java.awt.Dimension(32767, 230));
        pnTable.setPreferredSize(new java.awt.Dimension(465, 230));

        javax.swing.GroupLayout pnTableLayout = new javax.swing.GroupLayout(pnTable);
        pnTable.setLayout(pnTableLayout);
        pnTableLayout.setHorizontalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        pnTableLayout.setVerticalGroup(
            pnTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelOverviewLayout = new javax.swing.GroupLayout(PanelOverview);
        PanelOverview.setLayout(PanelOverviewLayout);
        PanelOverviewLayout.setHorizontalGroup(
            PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongTinChiTiet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelOverviewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOverviewLayout.createSequentialGroup()
                        .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelOverviewLayout.createSequentialGroup()
                                .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelOverviewLayout.createSequentialGroup()
                                        .addComponent(lblTenNhomQuyen)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtName)))
                            .addComponent(txtDes)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelOverviewLayout.createSequentialGroup()
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(PanelOverviewLayout.createSequentialGroup()
                        .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChiTietQuyen))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelOverviewLayout.setVerticalGroup(
            PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOverviewLayout.createSequentialGroup()
                .addComponent(lblThongTinChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblChiTietQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    public ArrayList<CTQuyenDTO> getListCTQuyen() {
        ArrayList<CTQuyenDTO> listCTQ = new ArrayList<>();
        String MaNQStr = txtID.getText().substring(2);
        int MaNQ = Integer.parseInt(MaNQStr);
        for (int i = 0; i < tableCTQuyen.getRowCount(); i++) {
            Object value = tableCTQuyen.getValueAt(i, 3);
            if (value instanceof Boolean && (Boolean) value) {
                String MaCNStr = tableCTQuyen.getValueAt(i, 0).toString().substring(2);
                int MaCN = Integer.parseInt(MaCNStr);
                String HanhDong = tableCTQuyen.getValueAt(i, 2).toString();
                CTQuyenDTO nq = new CTQuyenDTO(1, MaNQ, MaCN, HanhDong, 1);
                listCTQ.add(nq);
            }
        }
        return listCTQ;
    }

    public boolean checkValidate() {
        if (txtName.getText().isBlank()) {
            sharedFunction.displayErrorMessage("Không để trống tên nhóm quyền!!");
            return false;
        }
        if (txtDes.getText().isBlank()) {
            sharedFunction.displayErrorMessage("Không để trống mô tả nhóm quyền!!");
            return false;
        }
        ArrayList<CTQuyenDTO> listCTQ = getListCTQuyen();
        if (listCTQ.size() == 0) {
            sharedFunction.displayErrorMessage("Chưa chọn chức năng cho nhóm quyền!!");
            return false;
        }

        return true;
    }

    public boolean checkCurrentID() {
        int currentID = nqBUS.getCurrentID();
        int MaNQ = Integer.parseInt(txtID.getText().substring(2));

        return currentID + 1 == MaNQ;
    }

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (!checkValidate()) {
            return;
        }
        if (checkCurrentID()) {
            boolean addNQ = nqBUS.taoNhomQuyenMoi(this);
            if (addNQ) {
                ArrayList<CTQuyenDTO> listCTQ = getListCTQuyen();
                boolean addCTQ = ctqBUS.TaoCTQuyen(listCTQ);
                if (addCTQ) {
                    JOptionPane.showMessageDialog(null, "Tạo nhóm quyền thành công");
                    nqBUS.createTablePer(nqGUI.getModelNhomQuyen());
                    this.dispose();

                }
            }
        } else {
            boolean updateNQ = nqBUS.suaNhomQuyen(this);
            if (updateNQ) {
                ArrayList<CTQuyenDTO> listCTQ = getListCTQuyen();
                int MaNQ = Integer.parseInt(txtID.getText().substring(2));
                boolean updateCTQ = ctqBUS.SuaCTQuyen(listCTQ, MaNQ);
                if (updateCTQ) {
                    JOptionPane.showMessageDialog(null, "Sửa nhóm quyền thành công");
                    nqBUS.createTablePer(nqGUI.getModelNhomQuyen());
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseEntered
        // TODO add your handling code here:
        // Đặt con trỏ thành biểu tượng bàn tay khi di vào
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnLuuMouseEntered

    private void btnLuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseExited
        // TODO add your handling code here:
        // Đặt lại con trỏ thành con trỏ mặc định khi di ra
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnLuuMouseExited

    private void btnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseEntered
        // TODO add your handling code here:
        // Đặt con trỏ thành biểu tượng bàn tay khi di vào
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnHuyMouseEntered

    private void btnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseExited
        // TODO add your handling code here:
        // Đặt lại con trỏ thành con trỏ mặc định khi di ra
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_btnHuyMouseExited

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Đóng frame
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ChiTietQuyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelOverview;
    private Components.ButtonRadius btnHuy;
    private Components.ButtonRadius btnLuu;
    private javax.swing.JLabel lblChiTietQuyen;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblTenNhomQuyen;
    private javax.swing.JLabel lblThongTinChiTiet;
    private javax.swing.JPanel pnTable;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
