/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CTPhieuNhapBUS;
import BUS.PhieuNhapBUS;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @Nhóm 13
 */
public class ChiTietPhieuNhap extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietPhieuNhap
     */
    CTPhieuNhapBUS ctpnBUS = new CTPhieuNhapBUS();
    PhieuNhapBUS pnBUS = new PhieuNhapBUS();
    private static boolean update = false;
    private PhieuNhapGUI pnGUI;
    public ChiTietPhieuNhap(PhieuNhapGUI pnGUI) {
        this.pnGUI = pnGUI;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JTextField getTxtDonGia() {
        return txtDonGia;
    }

    public JTextField getTxtIDPhieuNhap() {
        return txtIDPhieuNhap;
    }

    public JTextField getTxtIDSanPham() {
        return txtIDSanPham;
    }

    public JTextField getTxtSoLuong() {
        return txtSoLuong;
    }

    public static boolean isUpdate() {
        return update;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        lblID1 = new javax.swing.JLabel();
        lblThongTinChiTiet1 = new javax.swing.JLabel();
        lblTenTheLoai1 = new javax.swing.JLabel();
        txtIDPhieuNhap = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        btnHuy = new Components.ButtonRadius();
        btnLuu = new Components.ButtonRadius();
        txtIDSanPham = new javax.swing.JTextField();
        lblID2 = new javax.swing.JLabel();
        lblID3 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn.setBackground(new java.awt.Color(255, 255, 255));
        pn.setPreferredSize(new java.awt.Dimension(400, 450));

        lblID1.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblID1.setForeground(new java.awt.Color(148, 181, 222));
        lblID1.setText("ID Phiếu nhập");

        lblThongTinChiTiet1.setBackground(new java.awt.Color(153, 204, 255));
        lblThongTinChiTiet1.setFont(new java.awt.Font("Josefin Sans SemiBold", 1, 18)); // NOI18N
        lblThongTinChiTiet1.setForeground(new java.awt.Color(102, 102, 102));
        lblThongTinChiTiet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongTinChiTiet1.setText("Thông tin chi tiết");
        lblThongTinChiTiet1.setAutoscrolls(true);
        lblThongTinChiTiet1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblThongTinChiTiet1.setOpaque(true);

        lblTenTheLoai1.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblTenTheLoai1.setForeground(new java.awt.Color(148, 181, 222));
        lblTenTheLoai1.setText("ID Sản Phẩm");

        txtIDPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtIDPhieuNhap.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIDPhieuNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 210, 235), 2));
        txtIDPhieuNhap.setDisabledTextColor(new java.awt.Color(187, 187, 187));
        txtIDPhieuNhap.setFocusable(false);
        txtIDPhieuNhap.setRequestFocusEnabled(false);
        txtIDPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPhieuNhapActionPerformed(evt);
            }
        });

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSoLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 210, 235), 2));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(153, 204, 255));
        btnHuy.setBorder(null);
        btnHuy.setForeground(new java.awt.Color(102, 102, 102));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_24px/cancel.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setColor(new java.awt.Color(153, 204, 255));
        btnHuy.setFocusPainted(false);
        btnHuy.setFont(new java.awt.Font("Josefin Sans SemiBold", 1, 18)); // NOI18N
        btnHuy.setRadius(40);
        btnHuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHuyMouseExited(evt);
            }
        });
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(153, 204, 255));
        btnLuu.setBorder(null);
        btnLuu.setForeground(new java.awt.Color(102, 102, 102));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_24px/fix.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setColor(new java.awt.Color(153, 204, 255));
        btnLuu.setFocusPainted(false);
        btnLuu.setFont(new java.awt.Font("Josefin Sans SemiBold", 1, 18)); // NOI18N
        btnLuu.setRadius(40);
        btnLuu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLuuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLuuMouseExited(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        txtIDSanPham.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtIDSanPham.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIDSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 210, 235), 2));
        txtIDSanPham.setDisabledTextColor(new java.awt.Color(187, 187, 187));
        txtIDSanPham.setFocusable(false);
        txtIDSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDSanPhamActionPerformed(evt);
            }
        });

        lblID2.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblID2.setForeground(new java.awt.Color(148, 181, 222));
        lblID2.setText("Số lượng");

        lblID3.setFont(new java.awt.Font("Josefin Sans SemiBold", 0, 18)); // NOI18N
        lblID3.setForeground(new java.awt.Color(148, 181, 222));
        lblID3.setText("Đơn Giá Nhập");

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtDonGia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDonGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 210, 235), 2));
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThongTinChiTiet1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLayout.createSequentialGroup()
                        .addComponent(lblID1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnLayout.createSequentialGroup()
                        .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnLayout.createSequentialGroup()
                                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblID2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIDPhieuNhap, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTenTheLoai1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIDSanPham, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addComponent(lblThongTinChiTiet1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblID1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtIDPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTenTheLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblID2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnLayout.createSequentialGroup()
                        .addComponent(lblID3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPhieuNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPhieuNhapActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnHuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseEntered
        // TODO add your handling code here:
        // Đặt con trỏ thành biểu tượng bàn tay khi di vào
    }//GEN-LAST:event_btnHuyMouseEntered

    private void btnHuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseExited
        // TODO add your handling code here:
        // Đặt lại con trỏ thành con trỏ mặc định khi di ra
    }//GEN-LAST:event_btnHuyMouseExited

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Đóng frame
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseEntered
        // TODO add your handling code here:
        // Đặt con trỏ thành biểu tượng bàn tay khi di vào
    }//GEN-LAST:event_btnLuuMouseEntered

    private void btnLuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseExited
        // TODO add your handling code here:
        // Đặt lại con trỏ thành con trỏ mặc định khi di ra
    }//GEN-LAST:event_btnLuuMouseExited

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        String soLuongStr = getTxtSoLuong().getText();
        String donGiaStr = getTxtDonGia().getText();
        String MaPNStr = getTxtIDPhieuNhap().getText();
        String MaSPStr = getTxtIDSanPham().getText();

        if (validateInput(soLuongStr, donGiaStr)) {
            int soLuong = Integer.parseInt(soLuongStr);
            double donGia = Double.parseDouble(donGiaStr);

            pnGUI.getModelImportDetai().setValueAt(soLuong, pnGUI.getTableChitiet().getSelectedRow(), 2);
            pnGUI.getModelImportDetai().setValueAt(soLuong*donGia, pnGUI.getTableChitiet().getSelectedRow(), 3);
            double TongTien = 0; 
            for(int i = 0; i < pnGUI.getTableChitiet().getRowCount(); i++) {
                TongTien += Double.parseDouble(pnGUI.getModelImportDetai().getValueAt(i, 3).toString());
            }
            pnGUI.getTfTongTien().setText(TongTien+"");
            this.dispose();
            
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void txtIDSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDSanPhamActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed
    boolean validateInput(String soLuongStr, String donGiaStr) {

        if (soLuongStr.equals("")) {
            displayErrorMessage("Không để rỗng số lượng");
            return false;
        } else {
            try {
                int soLuong = Integer.parseInt(soLuongStr);
                if (soLuong <= 0) {
                    displayErrorMessage("Số lượng không hợp lệ");
                    return false;
                }
            } catch (Exception e) {
                displayErrorMessage("Số lượng không hợp lệ");
                return false;
            }
        }
        if (donGiaStr.equals("")) {
            displayErrorMessage("Không để rỗng đơn giá nhập");
            return false;
        } else {
            try {
                double donGia = Double.parseDouble(donGiaStr);
                if (donGia <= 0) {
                    displayErrorMessage("Đơn giá không hợp lệ");
                    return false;
                }
            } catch (Exception e) {
                displayErrorMessage("Đơn giá không hợp lệ");
                return false;
            }
        }
        return true;
    }

    void displayErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChiTietPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.ButtonRadius btnHuy;
    private Components.ButtonRadius btnLuu;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblID3;
    private javax.swing.JLabel lblTenTheLoai1;
    private javax.swing.JLabel lblThongTinChiTiet1;
    private javax.swing.JPanel pn;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtIDPhieuNhap;
    private javax.swing.JTextField txtIDSanPham;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
